### ISSUE TITLE
Alter Typescript Code Snippet Component to either auto wrap a class or ignore highlighting altogether

### ISSUE THREAD

**Issue by alkgreer** [OasisDigital/ng-doc-portal#5]
![e41cad95-f174-4eeb-a275-55e6aa40b842](https://user-images.githubusercontent.com/26122765/222748786-be5fd56d-0b53-4ada-b8c4-d0a7815060d2.jpg)

Currently you cannot write complex typescript code unless it is wrapped in a class.

**Comment by zjkipping** [comment]
Going to close this. I feel like the snippets usually look better anyways with the class context:
```ts
        class ExampleComponent {
          @ViewChild('modalContent') modalContent?: TemplateRef<any>;
            modalRef?: DialogRef<any>;

          openModal() {
            this.modalRef = this.newModal.open(this.modalContent, {
              height: '250px',
              width: '300px',
            });
          }

          closeModal() {
            this.modalRef?.close();
          }
        }
```

vs

```ts
          @ViewChild('modalContent') modalContent?: TemplateRef<any>;
            modalRef?: DialogRef<any>;

          openModal() {
            this.modalRef = this.newModal.open(this.modalContent, {
              height: '250px',
              width: '300px',
            });
          }

          closeModal() {
            this.modalRef?.close();
          }
```

Simple fix and you get the proper formatting/highlighting. There would be no easy way to "auto-wrap" code inside a class. Especially if the code is pure and shouldn't be in a class to begin with.

Unfortunately we also can't get rid of prettier since it does a lot of good work in removing "white-space" we get back from the DOM rendering of the html code snippet content. I tried looking for alternatives and didn't find much.
